# Generated by Django 3.2rc1 on 2021-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(),
        ),
    ]
