# Generated by Django 3.2rc1 on 2021-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshop', '0002_auto_20210416_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='drink_name',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='price',
            new_name='drink_price',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='price',
            new_name='food_price',
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='drink',
            name='drink_photo',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='food_details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='food',
            name='food_photo',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
