# Generated by Django 3.2rc1 on 2021-04-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayshop', '0003_auto_20210416_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='drink_details',
        ),
    ]
