# Generated by Django 3.2rc1 on 2021-04-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshop', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
