# Generated by Django 3.2rc1 on 2021-04-22 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayshop', '0006_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_drink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zayshop.drink')),
                ('obj_food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zayshop.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
