# Generated by Django 3.2rc1 on 2021-04-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zayshop', '0009_auto_20210423_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('details', models.CharField(max_length=1000, null=True)),
                ('photo', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitemfood',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItemDrink',
        ),
        migrations.DeleteModel(
            name='CartItemFood',
        ),
    ]
